### PR TITLE
feat: option to hide background image

### LINKED ISSUE #39: Add toggle in preview tab to hide background image and replace with "checkerboard transparent" pattern
Something like this but with lighter gray instead of black: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/10x10_checkered_board_transparent.svg/500px-10x10_checkered_board_transparent.svg.png

### PR DESCRIPTION
**Pull request by saihaj**
### Summary of PR
Add a toggle to hide background image and replace it with a checker board.

### Tests for unexpected behavior
* Able to toggle on and off

Kapture 2020-06-16 at 12 01 05

**Preveiw**: https://shabad-os-theme-tool-git-saihaj-issue39.saihaj.vercel.app

### Time spent on PR
60 mins => 45 mins creating SVG 

### Linked issues
Fix #39 

### Reviewers
@bhajneet @Harjot1Singh

### CODE REVIEW

**Comment by bhajneet** [comment]
Missing some niceties like:

```
.app .editor-overlay.no-image {
background-size: auto;
background-size: 10%;
}
```

And need to use a proper pattern that doesn't repeat on all edges. If it's black on left side, it needs to be white on the right side. Same for top and bottom. Else it cannot pattern/repeat properly.

**Comment by saihaj** [comment]
so I tried changing size.... but how do I make it overlap?
image

**Comment by bhajneet** [comment]
> And need to use a proper pattern that doesn't repeat on all edges. If it's black on left side, it needs to be white on the right side. Same for top and bottom. Else it cannot pattern/repeat properly.

**Comment by bhajneet** [comment]
Meaning edit the image or find a new one lol

**Comment by saihaj** [comment]
Thoughts on this one?
image

**Review by harjot1singh — COMMENTED** [review]
Looks good to me and changes seem completed. If not, @bhajneet please open a new issue.

**Review by harjot1singh — APPROVED** [review]

**Pull request merged**
