### PR TITLE
fix: export tab styling

### LINKED ISSUE #41: Style of export tab doesn't match the rest
**Describe the bug**
Export tab doesn't have "pane" class

**Screenshots**
Pane:
image

No Pane:
image

### PR DESCRIPTION
**Pull request by saihaj**
### Summary of PR
Add class names to export tab to use the theme defaults. Added styles for the input box since the theme styles used by it are too light so needed to override those. Update the secondary theme color to purple color instead of it being the same as primary. 

### Tests for unexpected behavior
**After:**
image

Preview link: https://shabad-os-theme-tool-git-saihaj-issue41.saihaj.now.sh/

### Time spent on PR
60 minutes

### Linked issues
Fix #41 

### Reviewers
@bhajneet @Harjot1Singh

### CODE REVIEW

**Comment by bhajneet** [comment]
The beige colors do not match the dark purple color of the sliders, dropdowns, and toggles of every other tab.

**Comment by saihaj** [comment]
Is the styling as expected or do I need to make other changes?

**Review by harjot1singh — COMMENTED** [review]
I'm not sure we need to change the input colours

**Comment by saihaj** [comment]
Because it is light colors and they blend in with background

**Comment by saihaj** [comment]
just try removing those you will see what I mean. There can be better way to do that, but I don't know what it is

**Comment by bhajneet** [comment]
> 
> 
> I'm not sure we need to change the input colours

It should match dropdown's bottom border color at least

**Comment by bhajneet** [comment]
The buttons also look weird going from more saturated/bright to dark/less-saturated on hover/focus

EDIT: Meaning backwards of what UI interaction should be

**Comment by harjot1singh** [comment]
> Because it is light colors and they blend in with background

Yep. confused on why it's behaving a little different to selects

**Comment by saihaj** [comment]
What do you suggest we do?

**Comment by harjot1singh** [comment]
Other than the buttons, all good to go. Do you want the buttons fixed @bhajneet? Tbh dark theme probably wasn't the way to go, except for the navbar (you can sub-theme)

**Comment by harjot1singh** [comment]
One thing I noticed @saihaj, the overlay theme name is now a placeholder, and no longer text. is this what you intended?

**Comment by saihaj** [comment]
> hat you intended?

Yes changes were made by #42 but you are right we need text I might have destroyed while merging conflicts

**Comment by saihaj** [comment]
should be fixed

**Comment by bhajneet** [comment]
@harjot1singh there should be both a dark and light theme, try a search for
both

**Comment by harjot1singh** [comment]
That explains it, easy to fix now!

**Comment by harjot1singh** [comment]
### Unfocused
image

### Focused
image

### Modal
image

**Review by harjot1singh — APPROVED** [review]

**Pull request merged**
